config/routes.rb
Aleman::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out' => "devise/sessions#destroy"
  end

  resources :loans
  resources :payments do
    member do
      get 'form'
    end
  end
  
  root :to => 'home#index'
end

app/models/loan.rb
# encoding: UTF-8
class Loan < ActiveRecord::Base
  attr_accessible :amount_payable, :annual_inflation_rate, :annual_interest_rate, :discount_rate, :frequency
  attr_accessible :grace_period_type, :initial_payment, :payments_count, :sale_price, :start_at, :total_days, :user_id
  attr_accessible :total_time, :total_time_type, :initial_costs_attributes, :recurrent_costs_attributes, :days_per_year

  TIME_TYPES = {
    15 => 'Quincenas',
    30 => 'Meses',
    180 => 'Semestres',
    360 => 'Años'
  }

  FREQUENCIES = {
    15 => 'Quincenal',
    30 => 'Mensual',
    180 => 'Semestral',
    360 => 'Anual'
  }

  GRACE_PERIODS = {
    s: 'Sin plazo',
    t: 'Plazo total',
    p: 'Plazo parcial'
  }

  DAYS_PER_YEAR = {
    360 => '360 días',
    365 => '365 días',
  }

  belongs_to :user
  has_many :payments
  has_many :initial_costs
  has_many :recurrent_costs

  accepts_nested_attributes_for :initial_costs
  accepts_nested_attributes_for :recurrent_costs

  validates :sale_price, numericality: { greater_than: 0 }, presence: true
  validates :initial_payment, numericality: { greater_than_or_equal_to: 0 }, presence: true
  validates :total_time, presence: true, numericality: { greater_than: 0 }
  validates :annual_interest_rate, numericality: { greater_than_or_equal_to: 0 }, presence: true
  validates :annual_inflation_rate, numericality: { greater_than_or_equal_to: 0 }, presence: true
  validates :discount_rate, numericality: { greater_than_or_equal_to: 0 }, presence: true

  before_save :set_up_attributes
  after_save :set_up_payments

  def set_up_attributes
    self.total_days = self.total_time * self.total_time_type
    self.amount_payable = self.sale_price - self.initial_payment + self.total_initial_costs
  end

  def payments_count
    if self.payments_per_year && self.years_count
      self.payments_per_year * self.years_count
    else
      0
    end
  end

  def set_up_payments
    self.payments.destroy_all

    1.upto(self.payments_count) do |i|
      self.payments.create({
        payment_index: i,
        annual_interest_rate: self.annual_interest_rate,
        annual_inflation_rate: self.annual_inflation_rate,
        grace_period_type: self.grace_period_type
      })
    end
  end

  def payments_per_year
    if self.frequency
      (self.days_per_year / self.frequency).to_i
    else
      0
    end
  end

  def years_count
    if self.total_days
      self.total_days / self.days_per_year
    else
      0
    end
  end

  def total_initial_costs
    self.initial_costs.pluck(:amount).sum
  end

  def credit_life_insurance_percentage
    self.recurrent_costs.where(name: 'credit_life_insurance_percentage').pluck(:amount).sum.to_f
  end

  def risk_insurance_percentage
    self.recurrent_costs.where(name: 'risk_insurance_percentage').pluck(:amount).sum.to_f
  end

  def periodic_fee
    self.recurrent_costs.where(name: 'periodic_fee').pluck(:amount).sum.to_f
  end

  def freight
    self.recurrent_costs.where(name: 'freight').pluck(:amount).sum.to_f
  end

  def administrative_costs
    self.recurrent_costs.where(name: 'administrative_costs').pluck(:amount).sum.to_f
  end

  def results
    @results ||= {}

    @results[:credit_life_insurance_percentage] = ((self.credit_life_insurance_percentage * self.frequency) / 30).abs
    @results[:risk_insurance] = ((self.risk_insurance_percentage * self.sale_price) / self.payments_per_year).abs
    @results[:interests] = self.payments.pluck(:interest).sum.to_f.abs
    @results[:amortizations] = (self.payments.pluck(:amortization).sum.to_f + self.payments.pluck(:prepayment).sum.to_f).abs
    @results[:credit_life_insurances] = Payment.where(loan_id: self.id).includes(:loan).map(&:credit_life_insurance).sum.abs
    @results[:risk_insurances] = (@results[:risk_insurance] * self.payments_count).abs
    @results[:periodic_fees] = (self.periodic_fee * self.payments_count).abs
    @results[:freights] = ((-self.freight * self.payments_count) + (-self.administrative_costs * self.payments_count)).abs

    @results
  end

  def calculate_discount_rate
    (((self.discount_rate + 1) ** (self.frequency.to_d / self.days_per_year.to_d)) - 1).round(7)
  end

  def calculate_effective_annual_cost_rate
    (((1 + self.irr) ** self.payments_per_year) - 1).round(7)
  end

  def calculate_irr
    ([self.amount_payable] + self.payments.pluck(:cash_flow).to_a).irr.round(7)
  end

  def calculate_npv
    npv = self.amount_payable

    discount_rate = self.calculate_discount_rate

    self.payments.pluck(:cash_flow).each_with_index do |cash_flow, index|
      npv = npv + (cash_flow / ((1 + discount_rate) ** (index + 1)))
    end

    npv.round(7)
  end

  def pv
    pv = 0.0

    discount_rate = self.calculate_discount_rate

    self.payments.pluck(:cash_flow).each_with_index do |cash_flow, index|
      pv = pv + (cash_flow.abs / ((1 + discount_rate) ** (index + 1)))
    end

    pv.round(7)
  end

  def benefit_cost_rate
    self.pv / self.amount_payable
  end

  def profits
    @profits ||= {}

    @profits[:discount_rate] = self.calculate_discount_rate
    @profits[:irr] = self.irr
    @profits[:effective_annual_cost_rate] = self.calculate_effective_annual_cost_rate
    @profits[:npv] = self.npv
    @profits[:benefit_cost_rate] = self.benefit_cost_rate

    @profits
  end
end

app/controllers/loans_controller.rb
class LoansController < InheritedResources::Base
  before_filter :authenticate_user!

  before_filter :set_owner, only: [:create, :update]

  def index
    @loans = current_user.loans
    
    index!
  end

  def new
    @loan = Loan.new

    5.times { @loan.initial_costs.build }
    5.times { @loan.recurrent_costs.build }

    new!
  end

  private

  def set_owner
    params[:loan][:user_id] = current_user.id
  end
end

app/helpers/loans_helper.rb
module LoansHelper
  def conditional_format(number)
    if number.start_with?("-")
      "<span class=\"negative\">#{number}</span>".html_safe
    else
      "<span class=\"positive\">#{number}</span>".html_safe
    end
  end
end

app/views/loans/_form.html.erb
<%= simple_form_for(@loan, html: { class: 'loan-form', id: 'loan_form', novalidate: 'novalidate' }) do |f| %>
  <div class="column" id="column-1">
    <%= f.input :sale_price, label: 'Precio de venta', input_html: { value: number_with_precision(@loan.sale_price, precision: 2), min: 0.00, step: 0.01 } %>
    <%= f.input :initial_payment, label: 'Costo inicial (S/.)', input_html: { value: number_with_precision(@loan.initial_payment, precision: 2), min: 0.00 }, as: :string %>

    <%= f.input :amount_payable, label: 'Monto a pagar', input_html: { disabled: true, readonly: true, value: number_with_precision(@loan.amount_payable, precision: 2), min: 0.00 } %>

    <%= f.input :annual_interest_rate, label: 'TEA (%)', as: :string %>
    <%= f.input :annual_inflation_rate, label: 'Inflación anual (%)', as: :string %>
    <%= f.input :discount_rate, label: 'Tasa de descuento (%)', as: :string %>
  </div>
  <div class="column" id="column-2">
    <%= f.input :start_at, label: 'Fecha de inicio', use_short_month: true %>
    <div class="input numeric optional loan_total_time">
      <label class="numeric optional" for="loan_total_time">Tiempo</label><%= f.input_field :total_time, as: :decimal, type: :number, step: :any %>
      <%= f.input_field :total_time_type, collection: Loan::TIME_TYPES.invert, include_blank: false %>
    </div>
    <%= f.input :frequency, label: 'Frecuencia', collection: Loan::FREQUENCIES.invert, include_blank: false %>
    <%= f.input :grace_period_type, label: 'Plazo de gracia', collection: Loan::GRACE_PERIODS.invert, include_blank: false %>

    <%= f.input :payments_count, label: 'Número de cuotas', as: :numeric, input_html: { disabled: true, readonly: true } %>

    <%= f.submit 'Calcular', class: 'button belize-hole' %>
  </div>
  <div class="column" id="column-3">
    <%= f.input :days_per_year, label: 'Días por año', collection: Loan::DAYS_PER_YEAR.invert, include_blank: false %>
    <div class="tab-container">
      <nav class="tabs">
        <a href="#">Gastos Iniciales</a>
        <a href="#">Gastos Periódicos</a>
      </nav>
      <div class="tab-panel">
        <table class="table table-striped table-condensed" id="loan-initial-costs">
          <thead>
            <tr>
              <th>Denominación</th>
              <th>Monto</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= f.simple_fields_for :initial_costs do |initial_cost_form| %>
              <tr>
                <td><%= initial_cost_form.input :name, label: false, collection: InitialCost::NAMES.invert %></td>
                <td><%= initial_cost_form.input :amount, label: false, as: :string %></td>
                <td></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="tab-panel">
        <table class="table table-striped table-condensed" id="loan-recurrent-costs">
          <thead>
            <tr>
              <th>Denominación</th>
              <th>Monto</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= f.simple_fields_for :recurrent_costs do |recurrent_cost_form| %>
              <tr>
                <td><%= recurrent_cost_form.input :name, label: false, collection: RecurrentCost::NAMES.invert %></td>
                <td><%= recurrent_cost_form.input :amount, label: false, as: :string %></td>
                <td></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>

<% if @loan.persisted? %>
<h2>Resultados y rentabilidad</h2>

<div id="results-and-profits">
  <table class="table table-striped" id="loan-results">
    <thead>
      <tr>
        <th colspan="2">Resultados</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Porcentaje de seguro de desgravamen de cada periodo:</td>
        <td><%= number_to_percentage(@loan.results[:credit_life_insurance_percentage] * 100) %></td>
      </tr>
      <tr>
        <td>Seguro de riesgo:</td>
        <td><%= number_to_currency(@loan.results[:risk_insurance]) %></td>
      </tr>
      <tr>
        <td>Intereses:</td>
        <td><%= number_to_currency(@loan.results[:interests]) %></td>
      </tr>
      <tr>
        <td>Amortización del capital:</td>
        <td><%= number_to_currency(@loan.results[:amortizations]) %></td>
      </tr>
      <tr>
        <td>Seguro de desgravamen:</td>
        <td><%= number_to_currency(@loan.results[:credit_life_insurances]) %></td>
      </tr>
      <tr>
        <td>Seguro contra todo riesgo:</td>
        <td><%= number_to_currency(@loan.results[:risk_insurances]) %></td>
      </tr>
      <tr>
        <td>Comisiones periódicas:</td>
        <td><%= number_to_currency(@loan.results[:periodic_fees]) %></td>
      </tr>
      <tr>
        <td>Portes y gastos administrativos:</td>
        <td><%= number_to_currency(@loan.results[:freights]) %></td>
      </tr>
    </tbody>
  </table>

  <table class="table table-striped" id="loan-profits">
    <thead>
      <tr>
        <th colspan="2">Rentabilidad</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Tasa de descuento:</td>
        <td><%= number_to_percentage(@loan.profits[:discount_rate] * 100) %></td>
      </tr>
      <tr>
        <td><abbr title="TIR">Tasa interna de retorno</abbr> de la operación:</td>
        <td><%= number_to_percentage(@loan.profits[:irr] * 100, significant: true) %></td>
      </tr>
      <tr>
        <td><abbr title="Tasa de costo efectivo anual">TCEA</abbr>:</td>
        <td><%= number_to_percentage(@loan.profits[:effective_annual_cost_rate] * 100) %></td>
      </tr>
      <tr>
        <td><abbr title="Valor actual neto">VAN</abbr> de la operación:</td>
        <td><%= number_to_currency(@loan.profits[:npv]) %></td>
      </tr>
      <tr>
        <td><abbr title="Índice beneficio/costo">B/C</abbr> de la operación:</td>
        <td><%= (@loan.profits[:benefit_cost_rate]).round(4) %></td>
      </tr>
    </tbody>
  </table>

  <div id="analytics">
    <% if @loan.profits[:irr] > @loan.profits[:discount_rate] %>
      <p>La tasa interna de retorno <strong>es mayor que la tasa de descuento</strong>, lo que indica que en este caso la operación podría aceptarse.</p>
    <% end %>
    <% if @loan.profits[:irr] < @loan.profits[:discount_rate] %>
      <p>La tasa interna de retorno <strong>es menor que la tasa de descuento</strong>, lo que indica que en este caso la operación debería rechazarse.</p>
    <% end %>

    <% if @loan.profits[:npv].to_i < 0 %>
      <p>El Valor Actual Neto (VAN) de esta operación <strong>es menor que 0</strong>, lo que significa que podría generar pérdidas.</p>
    <% end %>
    <% if @loan.profits[:npv].to_i == 0 %>
      <p>El Valor Actual Neto (VAN) de esta operación <strong>es 0</strong>, lo que significa que no genera beneficios ni pérdidas.</p>
    <% end %>
    <% if @loan.profits[:npv].to_i > 0 %>
      <p>El Valor Actual Neto (VAN) de esta operación <strong>es mayor que 0</strong>, lo que significa que podría generar beneficios.</p>
    <% end %>

    <% if @loan.profits[:benefit_cost_rate] > 1.0 %>
      <p>El índice beneficio / costo <strong>es mayor a 1</strong>, lo que indica que en este caso la operación podría aceptarse.</p>
    <% end %>
    <% if @loan.profits[:benefit_cost_rate] < 1.0 %>
      <p>El índice beneficio / costo <strong>es menor a 1</strong>, lo que indica que en este caso la operación debería rechazarse.</p>
    <% end %>
  </div>
</div>

<% end %>

<h2>Pagos</h2>

<table class="table table-striped" id="loan-payments">
  <thead>
    <tr>
      <th>#</th>
      <th>Fecha</th>
      <th><abbr title="Tasa efectiva anual">TEA</abbr></th>
      <th><abbr title="Tasa efectiva del periodo">TEP</abbr></th>
      <th><abbr title="Inflación anualizada">IA</abbr></th>
      <th><abbr title="Inflación del periodo">IP</abbr></th>
      <th>Plazo de gracia</th>
      <th>Saldo inicial</th>
      <th>Interés</th>
      <th>Amortización</th>
      <th>Cuota</th>
      <th>Saldo final</th>
      <th>Flujo</th>
    </tr>
  </thead>
  <tbody>
    <% @loan.payments.each do |payment| %>
      <tr id="payment-<%= payment.id %>">
        <td class="payment_payment_index"><%= payment.payment_index %></td>
        <td class="payment_start_at"><%= payment.start_at %></td>
        <td class="payment_annual_interest_rate editable-field">
          <%= number_to_percentage(payment.annual_interest_rate * 100, significant: true) %>
        </td>
        <td class="payment_periodic_interest_rate">
          <%= number_to_percentage(payment.periodic_interest_rate * 100, significant: true) %>
        </td>
        <td class="payment_annual_inflation_rate editable-field">
          <%= number_to_percentage(payment.annual_inflation_rate * 100, significant: true) %>
        </td>
        <td class="payment_periodic_inflation_rate">
          <%= number_to_percentage(payment.periodic_inflation_rate * 100, significant: true) %>
        </td>
        <td class="payment_grace_period_type editable-field">
          <%= Loan::GRACE_PERIODS[payment.grace_period_type.to_sym] %>
        </td>
        <td class="payment_opening_balance"><%= conditional_format(number_to_currency(payment.opening_balance)) %></td>
        <td class="payment_interest"><%= conditional_format(number_to_currency(payment.interest)) %></td>
        <td class="payment_amortization"><%= conditional_format(number_to_currency(payment.amortization)) %></td>
        <td class="payment_quota"><%= conditional_format(number_to_currency(payment.quota)) %></td>
        <td class="payment_final_balance"><%= conditional_format(number_to_currency(payment.final_balance)) %></td>
        <td class="payment_cash_flow"><%= conditional_format(number_to_currency(payment.cash_flow)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="payment-form-modal" style="display: none;"></div>

<script type="text/javascript">
  var validations_for_loan = <%= Loan.validators.to_json.html_safe %>;
  var validations_for_payment = <%= Payment.validators.to_json.html_safe %>;
  var validations_messages = <%= YAML.load_file("#{Rails.root}/config/locales/es.yml").to_json.html_safe %>.es.errors.messages;

  $(document).ready(function() {
    var costs_tabs = new Tabs($('.tab-container'));

    var loan_masked_inputs = new MaskedInput($('#loan_annual_interest_rate, #loan_annual_inflation_rate, #loan_discount_rate'), function(value) {
      return (value * 100) + "%";
    }, function(value) {
      return parseFloat(value) / 100;
    });

    $('.loan_initial_costs_name, .loan_recurrent_costs_name').find('select').each(function() {
      var input = $(this).parents('tr').find('input.string');

      if ($(this).val().match(/percentage/)) {
        loan_masked_inputs.add(input);
      }
    });

    $('.loan_initial_costs_name, .loan_recurrent_costs_name').find('select').on('change', function() {
      var input = $(this).parents('tr').find('input.string');

      if ($(this).val().match(/percentage/)) {
        loan_masked_inputs.add(input);
      }
      else {
        loan_masked_inputs.remove(input);
      }
    });

    new FormValidator('loan', $('#loan_form'), validations_for_loan, validations_messages);

    EditableField($('.editable-field'), {
      annual_interest_rate: 'TEA',
      periodic_interest_rate: 'TEP',
      annual_inflation_rate: 'Inflación anual',
      periodic_inflation_rate: 'Inflación del periodo',
      grace_period_type: 'Plazo de gracia'
    }, function(form) {
      new FormValidator('payment', form, validations_for_payment, validations_messages);
    });
  });
</script>

app/views/loans/index.html.erb
<nav>
  <h1>Mis préstamos</h1>
  <a href="/loans/new" class="button belize-hole float right">Registrar préstamo</a>
</nav>

<% if @loans.empty? %>
  <div class="message-container">
    <p class="message">
      Aún no tienes préstamos registrados.
    </p>
    <a href="/loans/new" class="button belize-hole">Registrar préstamo</a>
  </div>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Precio de venta</th>
        <th>Monto a pagar</th>
        <th>Fecha de inicio</th>
        <th>Tiempo</th>
        <th>Número de cuotas</th>
        <th><abbr title="Tasa de costo efectivo anual">TCEA</abbr></th>
        <th><abbr title="Tasa interna de retorno">TIR</abbr></th>
        <th><abbr title="Valor actual neto">VAN</abbr></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @loans.each do |loan| %>
        <tr>
          <td><%= loan.sale_price %></td>
          <td><%= loan.amount_payable %></td>
          <td><%= loan.start_at %></td>
          <td><%= loan.total_time %> <%= Loan::TIME_TYPES[loan.total_time_type] %></td>
          <td><%= loan.payments_count %></td>
          <td><%= number_to_percentage(loan.profits[:effective_annual_cost_rate] * 100) %></td>
          <td><%= number_to_percentage(loan.profits[:irr] * 100, significant: true) %></td>
          <td><%= number_to_currency(loan.profits[:npv]) %></td>
          <td><a href="<%= loan_path(loan) %>">Ver</a></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/loans/new.html.erb
<h1>Nuevo préstamo</h1>

<%= render 'form' %>

app/views/loans/show.html.erb
<h1>Editar préstamo</h1>

<%= render 'form' %>